# Generated by Django 3.1.7 on 2021-03-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210327_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='graphs',
            new_name='graphsx',
        ),
        migrations.AddField(
            model_name='dataset',
            name='graphsy',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
