# Generated by Django 3.1.7 on 2021-03-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210327_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='clas_res',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='reg_res',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
